### ISSUE TITLE
Don't use node for streaming

### ISSUE THREAD

**Issue by athoune** [anforaProject/anfora#33]
Using another stack, just for streaming purpose is painful for hosting.
Python 3.6 provides aio, and tools like https://github.com/channelcat/sanic made async web easy.

Also, use Websocket, not SSE, it's better for proxying, and it's 2018, you don't have to scratch build http stream tool anymore : https://sanic.readthedocs.io/en/latest/sanic/routing.html#websocket-routes

**Comment by athoune** [comment]
I can make PR for that, if you need it.

**Comment by yabirgb** [comment]
Hi @athoune I've choosen node because it was familiar to me (I haven't tried sanic yet) and you need it to compile the client. It's true that this is adding one more thing to the stack so maybe I can take a look and try to do it with sanic.

About SSE, I've decided to use it because it's over html and I can send the auth headers along the request ( I need to identify users for some endpoints). With websockets if I'm not mistaking you have to send the bearer token on the "handshake" or something like this. It's true? If the auth part is easy I can change to websockets as soon as possible.

**Comment by yabirgb** [comment]
@athoune I've been investigating and I don't see a good way of auth users with panic :/

**Comment by yabirgb** [comment]
I'm working to redo this part using aiohttp and ws following the mastodon implementation

**Comment by yabirgb** [comment]
Currently I'm working on federation. We need to port this [file](https://github.com/anforaProject/anfora/blob/master/src/streaming/index.js) to python. In the same folder I've created some files with aiohttp. I want to support both sse and websockets as mastodon does
