### ISSUE TITLE
anfora.social registration fails 

### ISSUE THREAD

**Issue by pwFoo** [anforaProject/anfora#46]
Any working demo available?
https://anfora.social registration fails.

**Comment by yabirgb** [comment]
Hi @pwFoo , sadly the registrations are closed and for this reason the form is not working. I would like to have a running instance but I'll open it when I have time (again) after my final exams. After my exams I want to push some changes that I have and continue developing things so it's more usable. Sorry for the inconvenience. If you want send me an email to anforaproject@gmail.com I'll add you to a list and notify you once the instance opens registrations :D

**Comment by pwFoo** [comment]
Is there another test instance with enabled registration?

**Comment by pwFoo** [comment]
Or docker image / stack / compose to easy setup self hosted test instance?

**Comment by yabirgb** [comment]
At the moment there isn't any docker image since the software is in a early stage. There is a how to install guide here https://docs.anfora.app/getting-started/ so you can test or develop the software. If you decide to install it and you find any issue or you need help with something feel free to open a ticket
